### ISSUE TITLE
Mismatch between fasta chromosome names and gff chromosome names

### ISSUE THREAD

**Issue by milesroberts-123** [harvardinformatics/degenotate#16]
Hello! It's me again, the guy from #15 lol. I pulled from the main branch this morning and gave degenotate another go. 

I noticed that degenotate doesn't like it if the chromosome names in a fasta file don't **exactly** match the gff file. 

For example, I input the TAIR10 assembly and the Araport11 annotation of the _Arabidopsis thaliana_ genome (available on [phytozome)](https://phytozome-next.jgi.doe.gov/) into degenotate:

`scripts/degenotate/degenotate.py -a data/genome.gff3 -g data/genome.fa -o degenotateOutput`

and I got this error:

```
Traceback (most recent call last):
  File "scripts/degenotate/degenotate.py", line 66, in <module>
    globs = SEQ.extractCDS(globs);
  File "/mnt/ufs18/home-010/robe1195/Josephs_Lab_Projects/tajimasDacrossSpecies/workflow/scripts/degenotate/lib/seq.py", line 149, in extractCDS
    cur_exon_seq = globs['genome-seqs'][header][start:exon_coords[start]];
KeyError: 'Chr1'
```

I think what's happening is that degenotate is not ignoring everything after the first space in the fasta headers, because I can easily resolve this error by removing everything after the first space. Here's a solution using regular expressions in seqkit:

`scripts/seqkit replace -p " .*" -r "" data/genome.fa > data/genome_shortTitles.fa`

and then running degenotate:

`scripts/degenotate/degenotate.py -a data/genome.gff3 -g data/genome_shortTitles.fa -o degenotateOutputShortTitles`

While this issue is easy to fix, it might be good to add a more explicit error message for this scenario or have degenotate try removing characters after the first space in fasta headers automatically. I think this is a common check other tools employ

Again, thank you so much for your work on this tool! I think this degenotate will be an awesome popgen resource, so I thought I should help contribute to the debugging :)

**Comment by gwct** [comment]
Hey again,
Thanks for using the script!
I think we anticipated this issue with the `-d` option. Though it only covers a certain use case (first part of FASTA header matches GFF labels), this specifies a delimiter on which the FASTA headers will be split internally, with the string before the split being kept. So you could do something like:

```
scripts/degenotate/degenotate.py -a data/genome.gff3 -g data/genome.fa -o degenotateOutput -d " "
```

and degenotate should clip everything in the FASTA headers after the first space. This doesn't cover every scenario, but maybe it will help in this case.

**Comment by milesroberts-123** [comment]
Oh whoops, I missed that option! The command you suggested works beautifully.

Thanks for your help!

**Comment by gwct** [comment]
No worries! Glad it worked. We'll probably add some better error handling for this type of thing, so I'll keep this open for now.

**Comment by gwct** [comment]
We've added an explicit check for matching headers between FASTA and GFF inputs with some better error reporting in the latest version, so hopefully this will make this easier for others to handle in the future!
Thanks!
