### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by aguilar-gomez** [harvardinformatics/degenotate#39]
I tried running it but I have an error. Can you please tell me what is the problem?
```
#
# Welcome to degenotate -- Degeneracy annotation for coding transcripts.
# Version 1.2.1 released on May 2023
# degenotate was developed by Timothy Sackton, Gregg Thomas
# Website:       https://github.com/harvardinformatics/degenotate
#
# The date and time at the start is:  05.29.2023 | 14:49:45
# Using Python executable located at: /home/diana/anaconda3/envs/degenotate/bin/python3.10
# Using Python version:               3.10.6
#
# The program was called as:          /home/diana/anaconda3/envs/degenotate/bin/degenotate.py -a assembly_db_pasa1.assemblies.fasta.transdecoder.genome.gff3 -g Opum.rescaffold.fasta -o degenotate
#
# -----------------------------------------------------------------------------------------------------------------------------
# INPUT/OUTPUT INFO:
# Annotation file:                      /space/s2/diana/pumilio/rescaffolded_genome/assembly_db_pasa1.assemblies.fasta.transdecoder.genome.gff3
# Annotation file type:                 gff
# Genome file:                          /space/s2/diana/pumilio/rescaffolded_genome/Opum.rescaffold.fasta
# Output directory:                     degenotate
# Per-site degeneracy output:           degenotate/degeneracy-all-sites.bed
# Transcript count output:              degenotate/transcript-counts.tsv
# Log file:                             degenotate.log
# -----------------------------------------------------------------------------------------------------------------------------
# OPTIONS INFO:
# Option                                Current setting               Current action
# -m                                    3                             Transcripts shorter than this length will be ignored by degnotate.
# --quiet                               False                         Time, memory, and status info will be printed to the screen while degenotate is running.
# ------------------------------------------------------------------------------------------------------------------------------------------------------
# Date        Time      Current step                                      Status                                  Elapsed time (s)    Step time (s)   
# ------------------------------------------------------------------------------------------------------------------------------------------------------
# 05.29.2023  14:49:45  Detecting compression of annotation file          Success: No compression detected        0.03535             0.02788         
# 05.29.2023  14:49:45  Reading transcripts                               In progress...                          Traceback (most recent call last):
  File "/home/diana/anaconda3/envs/degenotate/bin/degenotate.py", line 59, in <module>
    globs = gxf.read(globs);
  File "/home/diana/anaconda3/envs/degenotate/lib/python3.10/site-packages/degenotate_lib/gxf.py", line 196, in read
    globs, num_transcripts = readFeatures(globs, reader, readline, ["transcript", "mRNA", "V_gene_segment", "C_gene_segment"], transcript_id_format, transcript_parent_format, field_splitter);
  File "/home/diana/anaconda3/envs/degenotate/lib/python3.10/site-packages/degenotate_lib/gxf.py", line 39, in readFeatures
    if line[0][0] == "#":
IndexError: string index out of range
```

**Comment by gwct** [comment]
Hi,
It seems like it is having trouble parsing some of the lines in your GFF file. It first tries to split each line by the tab character, so I would make sure every line in your GFF file is tab delimited. Specifically, I think this would happen if you had a blank line in your GFF file, probably at the end of the file since it wouldn't have a new-line character attached to it. Can you see if that is the case? If so, we can add a more specific check for blank lines.

**Comment by samebdon** [comment]
Hello, I have almost this exact error apart from it ends:
```
 if feature_info[-1][-1] == ";":
  IndexError: string index out of range
```
I have had a look and my file does not contain any empty lines. This is with a gff3 file but I can't get the tool running with a gtf file from the same braker2 annotation either.
Any help would be appreciated. thanks.

**Comment by gwct** [comment]
Hmm, that seems like its not finding anything in the last column of your gff, or the separator of the last column is different than expected. Can you paste a snippet from your gff file?

**Comment by samebdon** [comment]
Here is a snippet!
```
CAMXBY010000004.1	AUGUSTUS	gene	5192	7073	0.96	+	.	ID=g1;
CAMXBY010000004.1	AUGUSTUS	mRNA	5192	7073	0.96	+	.	ID=g1.t1;Parent=g1;
CAMXBY010000004.1	AUGUSTUS	start_codon	5192	5194	.	+	0	ID=g1.t1.start1;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	CDS	5192	5268	1	+	0	ID=g1.t1.CDS1;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	exon	5192	5268	.	+	.	ID=g1.t1.exon1;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	intron	5269	5388	1	+	.	ID=g1.t1.intron1;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	CDS	5389	5569	1	+	1	ID=g1.t1.CDS2;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	exon	5389	5569	.	+	.	ID=g1.t1.exon2;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	intron	5570	6466	1	+	.	ID=g1.t1.intron2;Parent=g1.t1;
CAMXBY010000004.1	AUGUSTUS	CDS	6467	6688	1	+	0	ID=g1.t1.CDS3;Parent=g1.t1;
```

**Comment by samebdon** [comment]
I processed this gff3 with AGAT and tried again. This time degenotate ran without giving any errors, but it did not write any of the default files to the output directory (other than the log). It did write the optional nt cds fasta and longest isoform nt fasta to the launch directory. Should I open this in a different issue?

**Comment by gwct** [comment]
I think in the case of the GFF from your snippet this is because of the trailing semi-colon in the last field. I've pushed a fix to our develop branch. If you want to try that out now you can clone that branch directly via `git clone -b develop https://github.com/harvardinformatics/degenotate`. Then to run, `cd` to the newly cloned `degenotate` directory and use `python degenotate.py`. Make sure you include the `python` part so you don't run the previously installed conda version (if that's how you installed it before).

Otherwise, you can wait until tomorrow or the day after for the fix to show up on bioconda.

I'm not sure why the AGAT version didn't work -- I'd have to see the gff again (here or in a new issue).

Also, do you know why the gtf file wasn't working? Again, here or in a new issue is fine.
